# Generated by Django 3.1.7 on 2021-04-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_commentanswer_commentquestion_downvote_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentanswer',
            name='comment_answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='commentquestion',
            name='comment_question',
            field=models.TextField(default=''),
        ),
    ]
