# Generated by Django 3.1.7 on 2021-04-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210411_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentquestion',
            name='detail',
            field=models.TextField(),
        ),
    ]
