# Generated by Django 3.1.7 on 2021-04-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210411_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentquestion',
            old_name='detail',
            new_name='comment_question_text',
        ),
    ]
