# Generated by Django 3.1.7 on 2021-04-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210411_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentanswer',
            old_name='comment_answer',
            new_name='comment_answer_text',
        ),
    ]
