# Generated by Django 3.1.7 on 2021-04-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_answer_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentanswer',
            old_name='comment_answer_text',
            new_name='detail',
        ),
    ]
