# Generated by Django 3.1.7 on 2021-04-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210412_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='parent',
        ),
    ]
