# Generated by Django 3.1.7 on 2021-04-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210412_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentanswer',
            name='question',
        ),
    ]
