# Generated by Django 3.1.7 on 2021-04-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210412_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answer'),
        ),
    ]
