# Generated by Django 3.1.7 on 2021-04-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210413_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='votes',
            new_name='downvotes',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='votes',
            new_name='downvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
